version: '3.4'
services:

  ###########################
  # Kafka
  ###########################
  zookeeper:
    image: docker.io/bitnami/zookeeper:3
    network_mode: host
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:2
    network_mode: host
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=localhost:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  ###########################
  # PROMETHEUS
  ###########################
  prometheus:
    image: prom/prometheus
    network_mode: host
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention=600d"
      - "--storage.tsdb.path=/prometheus"
      - "--web.external-url=http://prometheus.admin.achenar.net"
      - "--web.enable-lifecycle"
    ports:
      - "9090:9090"
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
      - ./etc/prometheus.alerts.yaml:/etc/prometheus/prometheus.alerts.yaml:ro

  ###########################
  # ALERTMANGER
  ###########################
  alertmanager:
    image: prom/alertmanager
    network_mode: host
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    ports:
      - "9093:9093"
    volumes:
      - ./etc/alertmanager.yaml:/etc/alertmanager/alertmanager.yml:ro
